# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/research',
                'doc_host': 'https://pmk-research-project.github.io',
                'git_url': 'https://github.com/pmk-research-project/research',
                'lib_path': 'research'},
  'syms': { 'research.core': { 'research.core.Ledger': ('core.html#ledger', 'research/core.py'),
                               'research.core.Ledger.__init__': ('core.html#ledger.__init__', 'research/core.py'),
                               'research.core.Ledger.sync': ('core.html#ledger.sync', 'research/core.py'),
                               'research.core.TimeSeries': ('core.html#timeseries', 'research/core.py'),
                               'research.core.TimeSeries.__init__': ('core.html#timeseries.__init__', 'research/core.py'),
                               'research.core.TimeSeriesTypes': ('core.html#timeseriestypes', 'research/core.py'),
                               'research.core.foo': ('core.html#foo', 'research/core.py')}}}
