# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/research',
                'doc_host': 'https://pmk-research-project.github.io',
                'git_url': 'https://github.com/pmk-research-project/research',
                'lib_path': 'research'},
  'syms': {'research.core': {'research.core.foo': ('core.html#foo', 'research/core.py')}}}
