# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_data.ipynb.

# %% auto 0
__all__ = ['load_trade_bars']

# %% ../nbs/10_data.ipynb 1
from .core import TimeSeries
from .utils import get_home_directory

def load_trade_bars():
    f"{get_home_directory()}/datastore"

