# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_derivatives.ipynb.

# %% auto 0
__all__ = ['DollarBars']

# %% ../nbs/11_derivatives.ipynb 1
import pandas as pd 

class DollarBars:
    def __init__(self, trade_partition: pd.DataFrame):
        self.tp = trade_partition.sort_values("participant_timestamp")
        self.cache = None

    @property
    def df(self):
        if self.cache is None:
            self.cache = self.calculate()
            return self.cache
        else:
            return self.cache
    
    def calculate(self) -> pd.DataFrame:
        df = self.tp.copy()
        df["notional_val"] = df["price"] * df["size"]
        df["notional_cumsum"] = df["notional_value"].cumsum()
        df["dollar_bar_idx"] = df["notional_cumsum"] / 1_000_000
        return df

